# Generated by Antigravity
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

# Install system dependencies for Playwright/Chromium and Timezone support
RUN apt-get update && apt-get install -y --no-install-recommends \
    tzdata \
    libnss3 \
    libnspr4 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libdbus-1-3 \
    libxkbcommon0 \
    libxcomposite1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxrandr2 \
    libgbm1 \
    libpango-1.0-0 \
    libcairo2 \
    libasound2 \
    && rm -rf /var/lib/apt/lists/*

# Set default timezone
ENV TZ=Asia/Singapore

WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy project files
COPY pyproject.toml uv.lock ./

# Install dependencies
RUN uv sync --frozen --no-install-project --no-dev

# Copy application code
COPY . .

# Install the project and Playwright browsers
RUN uv sync --frozen --no-dev && \
    uv run playwright install chromium --with-deps

# Expose the port
EXPOSE 5000

# Run the application
CMD ["uv", "run", "gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "--timeout", "120", "app:app"]
